#!/bin/bash

	sed -i \
		-e "s:-O3:\${CFLAGS}:" \
		-e "s:CC=gcc :CC=gcc :" \
		-e "s:LD=gcc :LD=\"gcc \${LDFLAGS} -lrcc\" :" \
		-e "s:-O :\${CFLAGS} :" \
		-e "s:LF2 = -s:LF2 = :" \
		unix/Makefile \
